---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goof
  name: goof
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goof
  template:
    metadata:
      labels:
        app: goof
    spec:
      containers:
      - image: ${DOCKER_ACCOUNT}/java-goof:latest
        imagePullPolicy: Always
        name: java-goof
        securityContext:
          readOnlyRootFilesystem: true
          privileged: false
          allowPrivilegeEscalation: false
          runAsUser: 123123
          runAsNonRoot: true
          capabilities:
            drop:
              - all
            add: []
        livenessProbe:
          exec:
            command:
              - ls
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goof
  name: goof
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "192.168.1.119"
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: goof
